namespace WinRTComponent
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        String MyProperty;
        String MyProperty2;
    }
}

namespace AnotherThing
{
    [default_interface]
    runtimeclass AnotherClass
    {
        AnotherClass();
        String MyProperty{ get; };
    }
}